import type { PreferredLanguage } from "@/lib/types";

export const QUALIFY_COPY: Record<
  PreferredLanguage,
  {
    stepOrder: Array<{ eyebrow: string; title: string; helper: string }>;
    moveTypes: Array<{ label: string; helper: string }>;
    flexibility: string[];
    properties: string[];
    sizeOptions: Array<{ label: string; helper: string }>;
    specialItems: string[];
    matching: { eyebrow: string; title: string; body: string; messages: string[] };
    shell: { badge: string; asideEyebrow: string; asideTitle: string; asideBody: string; back: string; continue: string; prepare: string; helper: string };
    errors: { step: string; contact: string; submit: string };
    labels: Record<string, string>;
    placeholders: Record<string, string>;
    options: Record<string, string>;
    sections: Record<string, string>;
  }
> = {
  en: {
    stepOrder: [
      { eyebrow: "Step 1", title: "Language, route, and timing", helper: "Choose the site language first, then add route and timing details." },
      { eyebrow: "Step 2", title: "Property and access", helper: "Only the access details that change pricing and feasibility." },
      { eyebrow: "Step 3", title: "Move size", helper: "Choose a quick size bucket first, then add detail where it helps." },
      { eyebrow: "Step 4", title: "Special items and add-ons", helper: "Group exceptions, handling needs, and extra services in one clean overview." },
      { eyebrow: "Step 5", title: "Contact and offer preferences", helper: "Finish with contact details and how the marketplace should handle offers." },
    ],
    moveTypes: [
      { label: "Home move", helper: "Apartment or house move." },
      { label: "Office move", helper: "Workplace or business relocation." },
      { label: "Heavy items", helper: "Piano, safe, gym gear, or similar." },
      { label: "International", helper: "Cross-border move in or out of Scandinavia." },
      { label: "Storage-led", helper: "Storage is a core part of the move." },
    ],
    flexibility: ["Exact date", "Flexible by a few days", "Flexible by a week or more"],
    properties: ["Apartment", "House", "Office", "Storage unit", "Other"],
    sizeOptions: [
      { label: "Few items", helper: "Student move, partial load, or a few large pieces." },
      { label: "Studio / 1-room", helper: "Compact apartment or similar." },
      { label: "2-room", helper: "Typical small apartment move." },
      { label: "3-room", helper: "Family apartment or townhouse segment." },
      { label: "Full home", helper: "Large household or full house." },
      { label: "Small office", helper: "Startup or small team office." },
      { label: "Large office", helper: "Larger workplace or phased office move." },
      { label: "Custom", helper: "Use your own volume estimate or short description." },
    ],
    specialItems: ["Piano", "Large fridge", "Washing machine", "Dryer", "Safe", "Gym equipment", "Fragile art", "Large wardrobes"],
    matching: {
      eyebrow: "Matching offers",
      title: "We are preparing your brief and ranking the best-fit movers.",
      body: "This mock flow uses route coverage, access difficulty, instant pricing rules, and budget fit to simulate a real marketplace.",
      messages: ["Reviewing move details", "Checking service areas", "Applying pricing rules", "Comparing fit and availability", "Preparing your matches"],
    },
    shell: {
      badge: "Guide",
      asideEyebrow: "Structured, calm, bid-ready",
      asideTitle: "Plan your move in five guided steps.",
      asideBody: "Every answer maps to pricing, matching, or feasibility without turning the experience into a long form.",
      back: "Back",
      continue: "Continue",
      prepare: "Prepare offers",
      helper: "One clear step at a time.",
    },
    errors: {
      step: "Complete this step first so the brief stays bid-ready.",
      contact: "Complete the missing contact or offer details first.",
      submit: "Unable to prepare your move brief",
    },
    labels: {
      language: "Site language",
      moveType: "What kind of move is this?",
      moveDate: "When are you moving?",
      dateFlexibility: "How fixed is the date?",
      pickupAddress: "Pickup address",
      dropoffAddress: "Drop-off address",
      describeMove: "Anything helpful to know about the route or timing?",
      pickup: "Pickup",
      dropoff: "Drop-off",
      propertyType: "Property type",
      floor: "Floor",
      elevator: "Is there an elevator?",
      elevatorUsable: "Can the elevator take furniture?",
      parkingAccess: "Parking and loading access",
      parkingDistance: "Parking distance in meters",
      accessNotes: "Any access notes?",
      moveSize: "How big is the move?",
      roomCount: "Room count",
      estimatedVolume: "Estimated volume (m3)",
      fullMove: "Full move or partial?",
      inventory: "Describe the inventory in your own words",
      specialItems: "Any special items?",
      specialNotes: "Anything the movers should know about those items?",
      packing: "Packing help",
      materials: "Need packing materials too?",
      storageDuration: "Storage duration",
      climate: "Climate-controlled storage?",
      disposalDetails: "What should be disposed of?",
      fullName: "Full name",
      email: "Email",
      phone: "Phone",
      contactMethod: "Preferred contact method",
      ready: "Ready to receive offers now",
      autoBids: "Allow instant estimates",
      preferredBudget: "Preferred budget",
      hardMaxBudget: "Hard max budget",
      canHelp: "Can you help carry if needed?",
      strictDeadline: "Strict handover or access deadline?",
      highValue: "High-value or insurance-sensitive items?",
      handoverTime: "Handover or access time",
      extraNotes: "Anything else the movers should know?",
      transportOnly: "Transport only",
      carryingIncluded: "Carrying and loading included",
      disassembly: "Disassembly / reassembly",
      storageNeeded: "Storage needed",
      disposalNeeded: "Disposal needed",
      cleaningNeeded: "Cleaning needed",
    },
    placeholders: {
      routeNotes: "Optional: city-centre loading restrictions, key timing, phased move, or rough description.",
      accessNotes: "Optional: narrow stairs, gate access, loading window, long carry.",
      inventory: "Example: 2-bedroom apartment, sofa, dining table, 25 boxes, one wardrobe, no basement storage.",
      specialNotes: "Optional: upright piano, 140 kg safe, mirror that needs protection, etc.",
      storageDuration: "Example: 2 weeks or 1 month",
      disposalDetails: "Optional: old sofa, bed frame, 10 boxes of waste, etc.",
      budget: "Optional",
      handoverTime: "Example: key handover by 14:00",
      extraNotes: "Optional: timing sensitivities, phased delivery, valuable contents, building rules, or any final context.",
      address: "Street, city, country",
    },
    options: {
      yes: "Yes",
      no: "No",
      usable: "Yes, usable",
      tooSmall: "No, too small",
      easyAccess: "Easy access",
      restricted: "Restricted",
      fullMove: "Full move",
      partialMove: "Partial move",
      noPacking: "No packing help",
      partialPacking: "Partial packing",
      fullPacking: "Full packing",
      undecided: "Not sure yet",
      phoneOrEmail: "Phone or email",
      phoneFirst: "Phone first",
      emailFirst: "Email first",
    },
    sections: {
      specialItems: "Special items",
      handling: "Handling preferences",
      services: "Extra services",
      offerPreferences: "Offer preferences",
      budget: "Budget preferences",
    },
  },
  da: {
    stepOrder: [
      { eyebrow: "Trin 1", title: "Sprog, rute og tidspunkt", helper: "Vælg sproget for siden først, og tilføj derefter rute og tidspunkt." },
      { eyebrow: "Trin 2", title: "Bolig og adgang", helper: "Kun de adgangsoplysninger der ændrer pris og gennemførlighed." },
      { eyebrow: "Trin 3", title: "Flyttens størrelse", helper: "Vælg først en hurtig størrelseskategori, og tilføj detaljer hvor det hjælper." },
      { eyebrow: "Trin 4", title: "Særlige genstande og tilvalg", helper: "Saml undtagelser, håndteringsbehov og ekstra services i et rent overblik." },
      { eyebrow: "Trin 5", title: "Kontakt og tilbudsønsker", helper: "Afslut med kontaktoplysninger og hvordan markedspladsen skal håndtere tilbud." },
    ],
    moveTypes: [
      { label: "Privatflytning", helper: "Lejlighed eller hus." },
      { label: "Kontorflytning", helper: "Arbejdsplads eller virksomhedsflytning." },
      { label: "Tunge genstande", helper: "Klaver, flygel, pengeskab, træningsudstyr eller lignende." },
      { label: "International", helper: "Grænseoverskridende flytning ind eller ud af Skandinavien." },
      { label: "Opbevaring", helper: "Opbevaring er en central del af flytningen." },
    ],
    flexibility: ["Fast dato", "Fleksibel et par dage", "Fleksibel en uge eller mere"],
    properties: ["Lejlighed", "Hus", "Kontor", "Depotrum", "Andet"],
    sizeOptions: [
      { label: "Få ting", helper: "Studieflytning eller delvist læs." },
      { label: "Studio / 1-værelse", helper: "Kompakt lejlighed eller lignende." },
      { label: "2-værelser", helper: "Typisk lille lejlighedsflytning." },
      { label: "3-værelser", helper: "Familielejlighed eller rækkehusdel." },
      { label: "Fuld husstand", helper: "Stor husstand eller helt hus." },
      { label: "Lille kontor", helper: "Startup eller mindre kontor." },
      { label: "Stort kontor", helper: "Større arbejdsplads eller etapevis kontorflytning." },
      { label: "Andet", helper: "Brug dit eget estimat eller en kort beskrivelse." },
    ],
    specialItems: ["Klaver / flygel", "Stort køleskab", "Vaskemaskine", "Tørremaskine", "Pengeskab", "Træningsudstyr", "Stor kunst", "Store skabe"],
    matching: {
      eyebrow: "Matcher tilbud",
      title: "Vi forbereder din brief og rangerer de bedst egnede flyttefirmaer.",
      body: "Dette mock-forløb bruger rutedækning, adgangssværhedsgrad, prisregler og budgetmatch til at simulere en reel markedsplads.",
      messages: ["Gennemgår flyttedetaljer", "Tjekker serviceområder", "Anvender prisregler", "Sammenligner match og kapacitet", "Klargør dine matches"],
    },
    shell: {
      badge: "Guide",
      asideEyebrow: "Struktureret, roligt, tilbudsklart",
      asideTitle: "Planlæg din flytning i fem guidede trin.",
      asideBody: "Hvert svar bruges til pris, match eller gennemførlighed uden at oplevelsen bliver til en lang formular.",
      back: "Tilbage",
      continue: "Fortsæt",
      prepare: "Forbered tilbud",
      helper: "Et tydeligt trin ad gangen.",
    },
    errors: {
      step: "Fuldfør dette trin først, så briefen forbliver tilbudsklar.",
      contact: "Udfyld de manglende kontakt- eller tilbudsdetaljer først.",
      submit: "Kunne ikke forberede din flyttebrief",
    },
    labels: {
      language: "Sprog for siden",
      moveType: "Hvilken type flytning er det?",
      moveDate: "Hvornår flytter du?",
      dateFlexibility: "Hvor fast er datoen?",
      pickupAddress: "Adresse for afhentning",
      dropoffAddress: "Adresse for levering",
      describeMove: "Er der noget vigtigt ved ruten eller timingen?",
      pickup: "Afhentning",
      dropoff: "Levering",
      propertyType: "Boligtype",
      floor: "Etage",
      elevator: "Er der elevator?",
      elevatorUsable: "Kan elevatoren tage møbler?",
      parkingAccess: "Parkering og læsseadgang",
      parkingDistance: "Parkeringsafstand i meter",
      accessNotes: "Andre adgangsnoter?",
      moveSize: "Hvor stor er flytningen?",
      roomCount: "Antal værelser",
      estimatedVolume: "Estimeret volumen (m3)",
      fullMove: "Fuldt flyttelæs eller delvis?",
      inventory: "Beskriv indboet med dine egne ord",
      specialItems: "Særlige genstande?",
      specialNotes: "Noget flyttefolkene bør vide om de genstande?",
      packing: "Hjælp til nedpakning",
      materials: "Skal materialer med?",
      storageDuration: "Varighed af opbevaring",
      climate: "Klimastyret opbevaring?",
      disposalDetails: "Hvad skal bortskaffes?",
      fullName: "Fulde navn",
      email: "Email",
      phone: "Telefon",
      contactMethod: "Foretrukken kontaktmetode",
      ready: "Klar til at modtage tilbud nu",
      autoBids: "Tillad hurtige estimater",
      preferredBudget: "Foretrukket budget",
      hardMaxBudget: "Maksbudget",
      canHelp: "Kan du hjælpe med at bære?",
      strictDeadline: "Fast nøgle- eller adgangsdeadline?",
      highValue: "Højværdi- eller forsikringsfølsomme genstande?",
      handoverTime: "Tid for nøgle eller adgang",
      extraNotes: "Andet flyttefirmaet bør vide?",
      transportOnly: "Kun transport",
      carryingIncluded: "Bæring og indlæsning inkluderet",
      disassembly: "Adskillelse / samling",
      storageNeeded: "Opbevaring nødvendig",
      disposalNeeded: "Bortskaffelse nødvendig",
      cleaningNeeded: "Rengøring nødvendig",
    },
    placeholders: {
      routeNotes: "Valgfrit: restriktioner i bymidten, nøgletid, etapevis flytning eller kort beskrivelse.",
      accessNotes: "Valgfrit: smalle trapper, portadgang, læssevindue eller lang bæreafstand.",
      inventory: "Eksempel: 2-værelses lejlighed, sofa, spisebord, 25 kasser, et klædeskab og intet kælderrum.",
      specialNotes: "Valgfrit: opretstående klaver, flygel, 140 kg pengeskab, spejl der kræver beskyttelse osv.",
      storageDuration: "Eksempel: 2 uger eller 1 måned",
      disposalDetails: "Valgfrit: gammel sofa, sengeramme, 10 kasser affald osv.",
      budget: "Valgfrit",
      handoverTime: "Eksempel: nøgleoverdragelse senest 14:00",
      extraNotes: "Valgfrit: tidsfølsomhed, etapevis levering, værdier, husregler eller sidste kontekst.",
      address: "Gade, by, land",
    },
    options: {
      yes: "Ja",
      no: "Nej",
      usable: "Ja, brugbar",
      tooSmall: "Nej, for lille",
      easyAccess: "Let adgang",
      restricted: "Begrænset",
      fullMove: "Hele flytningen",
      partialMove: "Delvis flytning",
      noPacking: "Ingen nedpakning",
      partialPacking: "Delvis nedpakning",
      fullPacking: "Fuld nedpakning",
      undecided: "Ikke afklaret endnu",
      phoneOrEmail: "Telefon eller email",
      phoneFirst: "Telefon først",
      emailFirst: "Email først",
    },
    sections: {
      specialItems: "Særlige genstande",
      handling: "Håndteringsvalg",
      services: "Ekstra services",
      offerPreferences: "Tilbudsvalg",
      budget: "Budgetønsker",
    },
  },
  sv: {
    stepOrder: [
      { eyebrow: "Steg 1", title: "Språk, rutt och tid", helper: "Välj språk för sidan först, och lägg sedan till rutt och tid." },
      { eyebrow: "Steg 2", title: "Bostad och åtkomst", helper: "Bara de åtkomstuppgifter som ändrar pris och genomförbarhet." },
      { eyebrow: "Steg 3", title: "Flyttens storlek", helper: "Välj först en snabb storleksnivå och lägg sedan till detaljer där det hjälper." },
      { eyebrow: "Steg 4", title: "Särskilda föremål och tillägg", helper: "Samla undantag, hanteringsbehov och extra tjänster i en lugn översikt." },
      { eyebrow: "Steg 5", title: "Kontakt och erbjudandepreferenser", helper: "Avsluta med kontaktuppgifter och hur marknadsplatsen ska hantera erbjudanden." },
    ],
    moveTypes: [
      { label: "Privatflytt", helper: "Lägenhet eller hus." },
      { label: "Kontorsflytt", helper: "Arbetsplats eller företagsflytt." },
      { label: "Tunga föremål", helper: "Piano, kassaskåp, gymutrustning eller liknande." },
      { label: "Internationell", helper: "Gränsöverskridande flytt in eller ut ur Skandinavien." },
      { label: "Förvaring", helper: "Förvaring är en central del av flytten." },
    ],
    flexibility: ["Exakt datum", "Flexibel några dagar", "Flexibel en vecka eller mer"],
    properties: ["Lägenhet", "Hus", "Kontor", "Förråd", "Annat"],
    sizeOptions: [
      { label: "Få saker", helper: "Studentflytt eller dellast." },
      { label: "Studio / 1 rum", helper: "Kompakt lägenhet eller liknande." },
      { label: "2 rum", helper: "Typisk mindre lägenhetsflytt." },
      { label: "3 rum", helper: "Familjelägenhet eller radhusdel." },
      { label: "Helt hem", helper: "Stor hushållsflytt eller helt hus." },
      { label: "Litet kontor", helper: "Startup eller mindre kontor." },
      { label: "Stort kontor", helper: "Stor arbetsplats eller etappvis kontorsflytt." },
      { label: "Egen uppskattning", helper: "Ange egen volym eller kort beskrivning." },
    ],
    specialItems: ["Piano", "Stort kylskåp", "Tvättmaskin", "Torktumlare", "Kassaskåp", "Gymutrustning", "Skör konst", "Stora garderober"],
    matching: {
      eyebrow: "Matchar erbjudanden",
      title: "Vi förbereder din brief och rangordnar de mest relevanta flyttfirmorna.",
      body: "Detta mock-flöde använder rutttäckning, åtkomstsvårighet, prisregler och budgetpassning för att simulera en riktig marknadsplats.",
      messages: ["Granskar flyttdetaljer", "Kontrollerar serviceområden", "Tillämpar prisregler", "Jämför passform och tillgänglighet", "Förbereder dina matcher"],
    },
    shell: {
      badge: "Guide",
      asideEyebrow: "Strukturerad, lugn, offertklar",
      asideTitle: "Planera din flytt i fem guidade steg.",
      asideBody: "Varje svar används för pris, matchning eller genomförbarhet utan att upplevelsen blir ett långt formulär.",
      back: "Tillbaka",
      continue: "Fortsätt",
      prepare: "Förbered erbjudanden",
      helper: "Ett tydligt steg i taget.",
    },
    errors: {
      step: "Fyll i detta steg först så att briefen förblir offertklar.",
      contact: "Fyll i saknade kontakt- eller offertuppgifter först.",
      submit: "Det gick inte att förbereda din flyttbrief",
    },
    labels: {
      language: "Språk för sidan",
      moveType: "Vilken typ av flytt är det?",
      moveDate: "När ska du flytta?",
      dateFlexibility: "Hur fast är datumet?",
      pickupAddress: "Hämtningsadress",
      dropoffAddress: "Leveransadress",
      describeMove: "Finns något viktigt om rutten eller tidplanen?",
      pickup: "Hämtning",
      dropoff: "Leverans",
      propertyType: "Bostadstyp",
      floor: "Våning",
      elevator: "Finns hiss?",
      elevatorUsable: "Kan hissen ta möbler?",
      parkingAccess: "Parkering och laståtkomst",
      parkingDistance: "Parkeringsavstånd i meter",
      accessNotes: "Några åtkomstnoteringar?",
      moveSize: "Hur stor är flytten?",
      roomCount: "Antal rum",
      estimatedVolume: "Uppskattad volym (m3)",
      fullMove: "Hel flytt eller delvis?",
      inventory: "Beskriv bohaget med egna ord",
      specialItems: "Några särskilda föremål?",
      specialNotes: "Något flyttarna bör veta om dessa föremål?",
      packing: "Packhjälp",
      materials: "Behöver du packmaterial också?",
      storageDuration: "Förvaringstid",
      climate: "Klimatkontrollerad förvaring?",
      disposalDetails: "Vad ska forslas bort?",
      fullName: "Fullständigt namn",
      email: "E-post",
      phone: "Telefon",
      contactMethod: "Önskad kontaktmetod",
      ready: "Redo att ta emot erbjudanden nu",
      autoBids: "Tillåt snabba estimat",
      preferredBudget: "Önskad budget",
      hardMaxBudget: "Maxbudget",
      canHelp: "Kan du hjälpa till att bära vid behov?",
      strictDeadline: "Fast nyckel- eller tillträdesdeadline?",
      highValue: "Högvärde- eller försäkringskänsliga föremål?",
      handoverTime: "Tid för nyckel eller tillträde",
      extraNotes: "Något annat flyttfirman bör veta?",
      transportOnly: "Bara transport",
      carryingIncluded: "Bärning och lastning ingår",
      disassembly: "Demontering / montering",
      storageNeeded: "Förvaring behövs",
      disposalNeeded: "Bortforsling behövs",
      cleaningNeeded: "Städning behövs",
    },
    placeholders: {
      routeNotes: "Valfritt: restriktioner i centrum, nyckeltid, etappflytt eller kort beskrivning.",
      accessNotes: "Valfritt: smala trappor, portkod, lastfönster eller långt bärmoment.",
      inventory: "Exempel: 2-rumslägenhet, soffa, matbord, 25 kartonger, en garderob och inget källarförråd.",
      specialNotes: "Valfritt: upprätt piano, kassaskåp på 140 kg, spegel som behöver skydd osv.",
      storageDuration: "Exempel: 2 veckor eller 1 månad",
      disposalDetails: "Valfritt: gammal soffa, sängram, 10 kartonger avfall osv.",
      budget: "Valfritt",
      handoverTime: "Exempel: nyckelöverlämning senast 14:00",
      extraNotes: "Valfritt: tidskänslighet, etappvis leverans, värdefullt innehåll, husregler eller slutlig kontext.",
      address: "Gata, stad, land",
    },
    options: {
      yes: "Ja",
      no: "Nej",
      usable: "Ja, fungerar",
      tooSmall: "Nej, för liten",
      easyAccess: "Enkel åtkomst",
      restricted: "Begränsad",
      fullMove: "Hela flytten",
      partialMove: "Del av flytten",
      noPacking: "Ingen packhjälp",
      partialPacking: "Delvis packning",
      fullPacking: "Full packning",
      undecided: "Inte bestämt än",
      phoneOrEmail: "Telefon eller e-post",
      phoneFirst: "Telefon först",
      emailFirst: "E-post först",
    },
    sections: {
      specialItems: "Särskilda föremål",
      handling: "Hanteringsval",
      services: "Extra tjänster",
      offerPreferences: "Erbjudandepreferenser",
      budget: "Budgetönskemål",
    },
  },
  no: {
    stepOrder: [
      { eyebrow: "Steg 1", title: "Språk, rute og tidspunkt", helper: "Start med å velge språk for siden, og legg deretter inn rute og tidspunkt." },
      { eyebrow: "Steg 2", title: "Bolig og tilgang", helper: "Bare tilgangsdetaljene som endrer pris og gjennomførbarhet." },
      { eyebrow: "Steg 3", title: "Flyttestørrelse", helper: "Velg først en rask størrelseskategori, og legg til detaljer der det hjelper." },
      { eyebrow: "Steg 4", title: "Spesielle gjenstander og tillegg", helper: "Samle unntak, håndteringsbehov og ekstra tjenester i en ryddig oversikt." },
      { eyebrow: "Steg 5", title: "Kontakt og tilbudspreferanser", helper: "Avslutt med kontaktinformasjon og hvordan markedsplassen skal håndtere tilbud." },
    ],
    moveTypes: [
      { label: "Privatflytting", helper: "Leilighet eller hus." },
      { label: "Kontorflytting", helper: "Arbeidsplass eller bedriftsflytting." },
      { label: "Tunge gjenstander", helper: "Piano, safe, treningsutstyr eller lignende." },
      { label: "Internasjonal", helper: "Grenseoverskridende flytting inn eller ut av Skandinavia." },
      { label: "Lagring", helper: "Lagring er en sentral del av flyttingen." },
    ],
    flexibility: ["Eksakt dato", "Fleksibel noen dager", "Fleksibel en uke eller mer"],
    properties: ["Leilighet", "Hus", "Kontor", "Lagerbod", "Annet"],
    sizeOptions: [
      { label: "Få ting", helper: "Studentflytting eller dellast." },
      { label: "Studio / 1-rom", helper: "Kompakt leilighet eller lignende." },
      { label: "2-rom", helper: "Typisk mindre leilighetsflytting." },
      { label: "3-rom", helper: "Familieleilighet eller rekkehusdel." },
      { label: "Full bolig", helper: "Stor husholdning eller helt hus." },
      { label: "Lite kontor", helper: "Startup eller mindre kontor." },
      { label: "Stort kontor", helper: "Stor arbeidsplass eller etappevis kontorflytting." },
      { label: "Egen vurdering", helper: "Bruk eget estimat eller en kort beskrivelse." },
    ],
    specialItems: ["Piano", "Stort kjøleskap", "Vaskemaskin", "Tørketrommel", "Safe", "Treningsutstyr", "Skjør kunst", "Store garderobeskap"],
    matching: {
      eyebrow: "Matcher tilbud",
      title: "Vi forbereder briefen din og rangerer de mest relevante flyttefirmaene.",
      body: "Dette mock-løpet bruker rutedekning, tilgangsvansker, prisregler og budsjettmatch for å simulere en ekte markedsplass.",
      messages: ["Gjennomgår flyttedetaljer", "Sjekker serviceområder", "Bruker prisregler", "Sammenligner match og kapasitet", "Klargjør matchene dine"],
    },
    shell: {
      badge: "Guide",
      asideEyebrow: "Strukturert, rolig, tilbudsklar",
      asideTitle: "Planlegg flyttingen i fem guidede steg.",
      asideBody: "Hvert svar brukes til pris, matching eller gjennomførbarhet uten at opplevelsen blir et langt skjema.",
      back: "Tilbake",
      continue: "Fortsett",
      prepare: "Forbered tilbud",
      helper: "Ett tydelig steg om gangen.",
    },
    errors: {
      step: "Fullfør dette steget først så briefen holder seg tilbudsklar.",
      contact: "Fullfør manglende kontakt- eller tilbudsdetaljer først.",
      submit: "Kunne ikke forberede flyttebriefen din",
    },
    labels: {
      language: "Språk for siden",
      moveType: "Hvilken type flytting er dette?",
      moveDate: "Når skal du flytte?",
      dateFlexibility: "Hvor fast er datoen?",
      pickupAddress: "Henteadresse",
      dropoffAddress: "Leveringsadresse",
      describeMove: "Er det noe viktig om ruten eller tidsplanen?",
      pickup: "Henting",
      dropoff: "Levering",
      propertyType: "Boligtype",
      floor: "Etasje",
      elevator: "Finnes det heis?",
      elevatorUsable: "Kan heisen ta møbler?",
      parkingAccess: "Parkering og lasteadkomst",
      parkingDistance: "Parkeringsavstand i meter",
      accessNotes: "Noen adgangsnotater?",
      moveSize: "Hvor stor er flyttingen?",
      roomCount: "Antall rom",
      estimatedVolume: "Estimert volum (m3)",
      fullMove: "Full flytting eller delvis?",
      inventory: "Beskriv inventaret med egne ord",
      specialItems: "Noen spesielle gjenstander?",
      specialNotes: "Noe flyttefolkene bør vite om disse tingene?",
      packing: "Pakkehjelp",
      materials: "Trenger du pakkematerialer også?",
      storageDuration: "Lagringsperiode",
      climate: "Klimakontrollert lagring?",
      disposalDetails: "Hva skal kjøres bort?",
      fullName: "Fullt navn",
      email: "E-post",
      phone: "Telefon",
      contactMethod: "Foretrukket kontaktmetode",
      ready: "Klar til å motta tilbud nå",
      autoBids: "Tillat raske estimater",
      preferredBudget: "Foretrukket budsjett",
      hardMaxBudget: "Maksbudsjett",
      canHelp: "Kan du hjelpe til med å bære ved behov?",
      strictDeadline: "Fast overtakelses- eller tilgangsfrist?",
      highValue: "Høyverdi- eller forsikringsfølsomme gjenstander?",
      handoverTime: "Tidspunkt for nøkkel eller adgang",
      extraNotes: "Noe annet flyttefirmaet bør vite?",
      transportOnly: "Kun transport",
      carryingIncluded: "Bæring og lasting inkludert",
      disassembly: "Demontering / montering",
      storageNeeded: "Lagring behøves",
      disposalNeeded: "Bortkjøring behøves",
      cleaningNeeded: "Rengjøring behøves",
    },
    placeholders: {
      routeNotes: "Valgfritt: restriksjoner i sentrum, nøkkeltid, etappeflytting eller kort beskrivelse.",
      accessNotes: "Valgfritt: smale trapper, portadgang, lastevindu eller lang bæreavstand.",
      inventory: "Eksempel: 2-roms leilighet, sofa, spisebord, 25 esker, ett skap og ingen kjellerbod.",
      specialNotes: "Valgfritt: piano, safe på 140 kg, speil som trenger beskyttelse osv.",
      storageDuration: "Eksempel: 2 uker eller 1 måned",
      disposalDetails: "Valgfritt: gammel sofa, sengramme, 10 esker avfall osv.",
      budget: "Valgfritt",
      handoverTime: "Eksempel: nøkkeloverlevering senest 14:00",
      extraNotes: "Valgfritt: tidsfølsomhet, etappevis levering, verdisaker, husregler eller siste kontekst.",
      address: "Gate, by, land",
    },
    options: {
      yes: "Ja",
      no: "Nei",
      usable: "Ja, brukbar",
      tooSmall: "Nei, for liten",
      easyAccess: "Enkel tilgang",
      restricted: "Begrenset",
      fullMove: "Hele flyttingen",
      partialMove: "Delvis flytting",
      noPacking: "Ingen pakkehjelp",
      partialPacking: "Delvis pakking",
      fullPacking: "Full pakking",
      undecided: "Ikke avklart ennå",
      phoneOrEmail: "Telefon eller e-post",
      phoneFirst: "Telefon først",
      emailFirst: "E-post først",
    },
    sections: {
      specialItems: "Spesielle gjenstander",
      handling: "Håndteringsvalg",
      services: "Ekstra tjenester",
      offerPreferences: "Tilbudspreferanser",
      budget: "Budsjettønsker",
    },
  },
};
